version: '3'
services:
  prometheus:
    image: prom/prometheus:v2.33.0
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    restart: always
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
volumes:
  prometheus_data:
